[package]
name = "pokerus"
version = "0.1.0"
edition = "2024"
license = "LGPL-2"

[lib]
name = "pokerus"

[dependencies]
byteorder = "1"
chrono = "0.4"
pokerus_macro = { path = "./pokerus_macro" }

[features]
default = [ "write" ]
write = []